-- Supabase Schema Migration (PostgreSQL)

-- 1. Users Table (Auth + Profile)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Password Reset Tokens
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used BOOLEAN DEFAULT FALSE
);

-- 3. Attendance Logs
CREATE TABLE IF NOT EXISTS attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id), -- No cascade, keep logs history
    date DATE NOT NULL,
    clock_in TIMESTAMP WITH TIME ZONE,
    clock_out TIMESTAMP WITH TIME ZONE,
    day_type TEXT CHECK (day_type IN ('working', 'half-day', 'leave', 'holiday')) DEFAULT 'working',
    late_status TEXT CHECK (late_status IN ('on-time', 'late', 'violation')),
    worked_minutes INTEGER,
    required_minutes INTEGER,
    entry_method TEXT CHECK (entry_method IN ('auto', 'manual')) DEFAULT 'auto',
    edited_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, date)
);

-- 4. User Settings
CREATE TABLE IF NOT EXISTS user_settings (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    min_daily_hours REAL DEFAULT 8.0,
    office_start_time TEXT DEFAULT '09:00',
    last_allowed_entry TEXT DEFAULT '10:00',
    first_half_min_hours REAL DEFAULT 4.0,
    effective_date DATE DEFAULT CURRENT_DATE,
    work_days TEXT DEFAULT '0,1,2,3,4',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Row Level Security (RLS) - Optional for Backend-only access 
-- (Assuming Service Role usage, RLS is bypassed, but good habit)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
